#!/usr/bin/env bash
# Install an nginx web server listening on port 80.
#
# Also, when querying nginx at its root / with a GET
# request, it returns a page that contains the string
# 'Hello World!'.
#
# Also, the script configures a directive of the Nginx server
# to redirect to another page with a 301 HTTP Code
#

findtext="server_name _;"
redirect_url="https://www.youtube.com/watch?v=QH2-TGUlwu4"
replacetext="$findtext\n\trewrite ^/redirect_me $redirect_url permanent;"

sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" > /var/www/html/index.html

# Use a different delimiter for sed to avoid conflicts
sudo sed -i "\#$findtext#c $replacetext" /etc/nginx/sites-available/default
sudo service nginx restart
