#!/usr/bin/env bash
# Displays the following content of the file /etc/passwd:
#   - username
#   - user id
#   - Home directory path for the user

myfile="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d":" -f1,3,6
done < "$myfile"