#!/usr/bin/env bash
# Displays:
#
#   - The content of the current directory
#   - In a list format
#   - Where only the part of the name after the first dash is displayed

content=$(ls | cut -d'-' -f2)

for file in $content; do
	echo "$file"
done