#!/usr/bin/env bash
# Displays numbers from 1 to 20 and:
#
#   - Displays 4 and then bad luck from China for the 4th loop iteration
#   - Displays 9 and then bad luck from Japan for the 9th loop iteration
#   - Displays 17 and then bad luck from Italy for the 17th loop iteration

content=$(find . | cut -d'-' -f2)

for file in $content; do
	echo "$file"
done